// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyrX5jm8gNGiZm_7Q_pzNSXik0xXM8qwE',
    appId: '1:116014508887:web:c38c3248572360e485ec12',
    messagingSenderId: '116014508887',
    projectId: 'fir-auth-bfb55',
    authDomain: 'fir-auth-bfb55.firebaseapp.com',
    storageBucket: 'fir-auth-bfb55.appspot.com',
    measurementId: 'G-TZ9RXWLW7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpPrPu6N8YW-g3FiSNWt0vAh8GpmC4br8',
    appId: '1:116014508887:android:0c0081b5d9a404dc85ec12',
    messagingSenderId: '116014508887',
    projectId: 'fir-auth-bfb55',
    storageBucket: 'fir-auth-bfb55.appspot.com',
  );
}
