name: google_maps_in_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4+2

flutter:
  uses-material-design: true
