name: flutter_digimon
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  http: ^1.1.0
  intl: ^0.18.1
  # flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
