name: flutter_provider_example1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0
  english_words: ^4.0.0
  provider: ^6.1.1

flutter:
  uses-material-design: true
